# Generated by Django 4.0.5 on 2022-06-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='phone_number',
            new_name='p_o_box',
        ),
    ]
