# Generated by Django 4.0.5 on 2022-06-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgnt', '0002_rename_phone_number_invoice_p_o_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='total_HTVA',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_TVA',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_TVAC',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
