# Generated by Django 4.0.5 on 2022-06-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgnt', '0003_rename_total_invoice_total_htva_invoice_total_tva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Quantity_check',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Nombre total de chéquiers:'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_HTVA',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Total HTVA:'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_TVA',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Total TVA:'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_TVAC',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Total TVAC:'),
        ),
    ]
