# Generated by Django 4.0.5 on 2022-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgnt', '0004_invoice_quantity_check_alter_invoice_total_htva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Invoice', 'Invoice')], default='', max_length=50, null=True),
        ),
    ]
