# Generated by Django 4.0.5 on 2022-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgnt', '0005_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Facture', 'Facture')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='p_o_box',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='P.O.Box: '),
        ),
    ]
