# Generated by Django 4.0.5 on 2022-07-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgnt', '0006_alter_invoice_invoice_type_alter_invoice_p_o_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Quantity_check',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Nombre de chéquiers:'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_P_U',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='item_price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_P_V_HTVA',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='item_price_nvat'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_P_V_TVAC',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='item_price_wvat'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_T_V_A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='vat'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_chequier',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='item_quantity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_P_U',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='item_price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_P_V_HTVA',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='item_price_nvat'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_P_V_TVAC',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='item_price_wvat'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_T_V_A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='vat'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_chequier',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='item_quantity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Customer Name'),
        ),
    ]
