# Generated by Django 4.0.5 on 2022-07-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgnt', '0009_alter_invoice_balance_alter_invoice_line_one_p_u_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_one_P_V_HTVA',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=5, null=True, verbose_name='item_price_nvat'),
        ),
    ]
