# Generated by Django 4.0.5 on 2022-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgnt', '0010_alter_invoice_line_one_p_v_htva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_one_P_V_HTVA',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='item_price_nvat'),
        ),
    ]
